### PR TITLE
Update the SameBoy core to version 0.14.6

### PR DESCRIPTION
**Pull request by RokkumanX**

### CODE REVIEW

**Comment by RokkumanX** [comment]
Here is a compiled core (64-bit) if anyone wants to check it out in the mean time while waiting for the pull request to be merged.

It's compiled with MSYS2 MinGW 64-bit.

[sameboy_libretro.dll.zip](https://github.com/libretro/SameBoy/files/7394417/sameboy_libretro.dll.zip)

**Comment by inactive123** [comment]
hi, does your rebased core as per this PR still have these improvements as well?

https://github.com/libretro/SameBoy/pull/68

Everything still works and runs well?

**Comment by RokkumanX** [comment]
My rebased core have everything from this branch and the latest changes from LIJI32.

Sadly I haven't had the time testing the core out yet, let alone testing the latest RetroArch out.

However, I have just now built the core with MSYS2 (64-bit) which should be 100% up to date and I also included the pre-built boot roms which ships with SameBoy.

If someone that has more time then me right now are willing just to test it quickly I would be thrilled.

Here you go:

[sameboy_libretro.dll.zip](https://github.com/libretro/SameBoy/files/7425468/sameboy_libretro.dll.zip)

Shouldn't be any problems but it should be tested.

**Comment by jdgleaver** [comment]
There is nothing in this PR that affects #68, and the updated core seems to run perfectly (tested on Linux). Very nice :)

I think it's fine to merge.

**Comment by Awakened0** [comment]
Tested on Windows and everything looks good there too.

**Comment by RokkumanX** [comment]
LGTM?

**Comment by jdgleaver** [comment]
Yes, why has this not been merged...?

**Comment by inactive123** [comment]
My bad for this taking a while.

**Pull request merged**
