### PR TITLE
Update the SameBoy core to 0.14.3

### PR DESCRIPTION
**Pull request by RokkumanX**
As requested in https://github.com/libretro/SameBoy/issues/64

### CODE REVIEW

**Comment by Ryunam** [comment]
Just out of curiosity, can someone test whether this update also fixes this little issue that I encountered here? https://github.com/libretro/SameBoy/issues/62

**Comment by RokkumanX** [comment]
@Ryunam

[sameboy.zip](https://github.com/libretro/SameBoy/files/6637072/sameboy.zip)

Test this out, just built it myself.

**Comment by RokkumanX** [comment]
@Ryunam 

Can confirm your issue even with all the latest updates, I used my Japanese copy of the game (Super Donkey Kong GB)

It sounds terrible as you described, nice catch though as I rarely play this game (come to think of it I probably beat it with Gambatte the last time)

**Comment by Ryunam** [comment]
Thank you for testing this! I don’t have access to my PC until later on today, so I do not have the means to experiment with it currently, but I guess I should try to perform a bisect and see exactly when this broke...

I know for certain that the issue did not exist prior to the last big resync with upstream. Strangely enough, it seems specific to the Libretro core and does not seem to occur with the standalone Windows version.

**Comment by RokkumanX** [comment]
I will try to help you find the regression so from now on let's continue the discussion in your issue.

**Comment by Eduxki** [comment]
> @Ryunam
> 
> [sameboy.zip](https://github.com/libretro/SameBoy/files/6637072/sameboy.zip)
> 
> Test this out, just built it myself.

Can you create one for Android please?

**Comment by RokkumanX** [comment]
@Eduxki 

I just tried building the core for you but it seems that I'm missing things to be able and build for Android, Windows seems perfectly fine (when it wants to)

I'm using MSYS2 MinGW.

What we really need though is someone from the admin to merge this so the core can be updated for everybody and all platforms it supports.

I already know this works since I built it myself for Windows from my own repository, so if I had the access I would merge this in a heartbeat.

**Comment by inactive123** [comment]
@Ryunam Is this ready to be merged?

**Comment by RokkumanX** [comment]
@twinaphex 

Yes sir!

I have verified it myself and I have had zero issues.

**Comment by Ryunam** [comment]
@twinaphex Yes, everything seems to be working properly. 

I have performed a few tests here on Windows with a self-built core, including the latest commits that @RokkumanX backported, while also making sure to verify that Runahead and other things were still functioning. 

I believe it's ready!

**Comment by RokkumanX** [comment]
Added latest commits from upstream, core should be absolutely 100% up to date.

Everything works on my side.

Merge???

**Comment by RokkumanX** [comment]
Thank you very much for this!

**Pull request merged**
