### PR TITLE
ios support

### PR DESCRIPTION
**Pull request by jet082**

### CODE REVIEW

**Comment by andres-asm** [comment]
Does nothing, libretro buildbot uses it's own branch
LIJI32 didn't want to change the path on purpose on his own branch

**Comment by andres-asm** [comment]
I'm reverting this PR, please submit again against buildbot branch

**Comment by jet082** [comment]
I see. In that case, it might be best to copy the file as well. The reason being, the published method for compiling libretro cores uses ``libretro-build-xxx.sh`` (for example ``libretro-build-ios-arm64.sh``). This is for individual building outside of the buildbot.

And for that, it uses the path I provided. With mesen-s, the solution was to add a line in the MakeFile to copy the file to accommodate both paths.

**Comment by jet082** [comment]
(Likewise, the script referenced uses this branch and not the buildbot one. So to support both end users and the buildbot, modifying something is necessary...)

**Comment by jet082** [comment]
(See this article for an example of what I am talking about - https://docs.libretro.com/development/retroarch/compilation/ios/. Similar instructions exist across all cores)

**Comment by andres-asm** [comment]
Honestly noone uses those libretro-build scripts, we all use the buildbot scripts.I am hell bent on keeping master branch pristine.

Those libretro-build scripts don't handle branches or submodules.

**Pull request merged**
