### PR TITLE
Buildbot **do not merge, read instructions**

### PR DESCRIPTION
**Pull request by andres-asm**
Do not merge

```
git checkout buildbot
git remote add downstream https://github.com/fr500/SameBoy.git
git fetch downstream
git reset --hard downstream/buildbot
```

This is done so all those dumb merge commits disappear from the commit history

### CODE REVIEW

**Comment by inactive123** [comment]
I did the commands outlined here -

https://github.com/libretro/SameBoy/pull/27

let me know if I need to do this as well.

**Comment by andres-asm** [comment]
There are two branches in this one, master that tracks @LIJI32's, and the buildbot branch that adds the stuff required for the buildbot to work.

So yeah this is required to.

**Comment by inactive123** [comment]
Done.

**Comment by andres-asm** [comment]
Hmm it's not correct for some reason... it should be basically 1 commit ahead of LIJIs

**Pull request merged**
